### ISSUE TITLE
Flavian

### ISSUE THREAD

**Issue by simonjoom** [Weakky/prisma-ecommerce#29]
Bonjour Flavian, je suis très intéressé par ce repo et le code que tu développes, moi même je travaille avec Prisma, 
Je t'ai contacté sur twitter récemment, pourrai-tu m'appeler sur mon tel au 0675505209?. Je cherche quelqu'un comme toi. 
Tu peux fermer cette issue après l'avoir lue

**Comment by Weakky** [comment]
Hello, tu ne m'as pas contacté sur twitter. @ FlavianDesverne
