### ISSUE TITLE
update apollo to 2.0 simz

### ISSUE THREAD

**Issue by simonjoom** [Weakky/prisma-ecommerce#30]
I'm currently working on your project.

did update apollo and code relative to work with last version.
app working with last apollo2 now. 
I already setup the Facebook login with prisma in my repo, i can add it here too

**Comment by Weakky** [comment]
Sounds amazing!

Are you on the Prisma's slack ? That'd be cool if we could talk about that there !

**Comment by simonjoom** [comment]
please call me !! 0675505209 je suis francais!

**Comment by Weakky** [comment]
Si possible, je préférerais ne pas avoir à partager mon numéro perso pour ce genre de chose 😄

**Comment by simonjoom** [comment]
ok c'est chiant ba va y on tchat sur slack
genre.. je vais pas te spammer lol

**Comment by Weakky** [comment]
Je pense t'avoir trouvé, si je me suis trompé c'est @weakky

**Comment by simonjoom** [comment]
je viens de t'avoir trouvé, je t'ai envoyé un message
