### ISSUE TITLE
Create the views to handle user's account

### ISSUE THREAD

**Issue by Weakky** [Weakky/prisma-ecommerce#6]
The last tab on the RN app will be dedicated to user's account, allowing him to manage all kind of stuff.

- [x] List his orders (with ability to add an order to the cart)
- [x] Edit his account information
- [x] Grab shops information (opening hours, address, etc etc. This may be put in the `ShopMetadata` model)
- [x] Allow to change his shop
- [x] Logout
- [x] Terms of Service
- [ ] More ideas ?

**Comment by Weakky** [comment]
A prototype view was implemented using `react-native-settings-list`

<img height="500" src="https://user-images.githubusercontent.com/25233379/40881672-028ba284-66cd-11e8-8e71-a4788816537b.png"/>

**Comment by Weakky** [comment]
As well as the view to restiture all user's orders

<img height="500" src="https://user-images.githubusercontent.com/25233379/40881690-7d74bf94-66cd-11e8-9242-001ac3011720.png"/>

**Comment by Weakky** [comment]
<img height="500" src="https://user-images.githubusercontent.com/25233379/41260002-f9f49184-6dd5-11e8-9220-7bb2d6115315.png"/>

**Comment by DupK** [comment]
Improvement of the prototype

![settings](https://user-images.githubusercontent.com/21973081/44937219-80992100-ad78-11e8-9be8-aec1674336ca.png)
